### ISSUE TITLE
Standards listed in Probe message envelope

### ISSUE THREAD

**Issue by JavierEspina** [IHE/DEV.SDPi#78]
## Section Number

2:A.2.2.1.2 Message Outline

## Priority

Medium

## Issue

Why does the WS-Discovery Hello message (2:A.2.1.1) also list DPWS in its Envelope while this message does not?

## Proposed Change

Clarify

**Comment by d-gregorczyk** [comment]
It should. I'll fix this

**Comment by d-gregorczyk** [comment]
Actually, it may not. This is the request message, so the requested only requires the provider to have _at least_ mdpws:Device in its Types (which is sufficient since MDPWS normatively includes DPWS). There was however another inconsistency I needed to fix: `sdc.mds.pkp:1.2.840.10004.20701.1.1` should appear as a scope in Hello messages
